### ISSUE TITLE
New team from TU Kaiserslautern

### ISSUE THREAD

**Issue by thejeshk** [tum-phoenix/drive_gazebo_sim#13]
Hi, 

Could you please tell us how did you build the simulation in Gazebo?

Best Regards
TK

**Comment by MaslinuPoimal** [comment]
Hi,

most of the URDF is based upon a CAD model of our current car. Common sensors are available as gazebo plugins, the only thing you might have to do is adjust a few values. To generate worlds, head over to [tum-phoenix/drive_sim_road_generation](https://github.com/tum-phoenix/drive_sim_road_generation) the readme basically explains how to do it. You also need a workspace with drive_gazebo_worlds or otherwise you will be missing the traffic sign and ramp meshes provided by that package. Currently pushed schema was a WIP and might miss a few signs, if something fails during rendering, just rerun the generator. I will try to finish my changes soon so that advanced mode features are all added by the renderer. 

Best regards,

Mykyta

**Comment by MaslinuPoimal** [comment]
If you have any questions, write me at mykyta.denysov[ at ]tum-phoenix.de. Car is driving in sim now, so I'm closing this.
